<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<title>ErpicoPBX 4.0</title>

	<!-- Webix files-->
	<link rel="stylesheet" href="./webix/webix.min.css" type="text/css">
	<script src="./webix/webix.min.js" type="text/javascript"></script>

	<link rel="stylesheet" href="./webix/skins/flat.css">
	<link rel="stylesheet" href="./webix/skins/custom_style.css">

	<link rel="stylesheet" href="./webix/fonts/fontawesome-all.css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
	<link href='http://fonts.googleapis.com/css?family=Lato:400,700' rel='stylesheet' type='text/css'>

    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">
	<script type="text/javascript" src="./helpers/nicedit.js"></script>
	<script type="text/javascript" src="./helpers/language.js"></script>
	<script type="text/javascript" src="./helpers/i18n/ru.js"></script>

	<!-- Error tracking -->
	<script src="https://cdn.ravenjs.com/3.10.0/raven.min.js"></script>

    <!-- Chat -->
    <script type="text/javascript" src="./webix/chat/chat.js"></script>
    <link rel="stylesheet" href="./webix/chat/chat.css" type="text/css">
	
	<!-- The App -->
	
	<link rel="stylesheet" href="./codebase/admin.css?v=aa1745e0">
	<link rel="stylesheet" href="./assets/erpico.css?v=aa1745e0">
	<script type="text/javascript" src="./codebase/admin.js?v=aa1745e0"></script>

	<!-- Data and additional
	<script src="" type="text/javascript"></script>
	-->
	
	
</head>
<body>


</body>
</html>